spring:
  application:
    name: notification-center
server:
  port: 9002
app: 
  id: notification-center
apollo:
  meta: http://192.168.0.11:9100
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/api-o/user-me
      prefer-token-info: false